getAllUsers:
    path: /users
    controller: App\Controller\ApiController::getAllUsers
    methods: GET

getOneUserById:
   path: /user/{id}
   controller: App\Controller\ApiController::getOneUser
   methods: GET